### ISSUE TITLE
[design] MainStatusView 수정

### ISSUE THREAD

**Issue by leewanjae** [DeveloperAcademy-POSTECH/2024-MacC-A2-PohangEgrets#64]
## 🍏 About
* MainStatusView 수정 

## 🍀 Branch Name
design/#64

## 🌱 To do
- [ ] MainStatusView 수정

**Comment by acciohyun** [comment]
무엇을 하면 될까용

**Comment by leewanjae** [comment]
음.. 앱 흐름 잡는거 해주실래요? 
StatusBar 화면이 초기에 같이 뜨는게 아니라 Window이후에 생성 시로 바뀌게?

**Comment by acciohyun** [comment]
일단 한번 해보겠습니다
앱 처음 실행할때도 있는 이슈인가요?

**Comment by leewanjae** [comment]
아! 지금 그 앱 크래쉬하는거 기본 값을 넣어서 임시방편으로 예방해놓은게 Host 유저를 그 기본 값에서 긁어와서
방을 만들면 Host가 그 방을 만든 유저가 아니고 기본 값 방에 있는 Host유저로 설정되더라고요.

**Comment by acciohyun** [comment]
두가지 문제인건가요?
1. 앱 실행할때 MainStatusView를 생성된다 (화면에 보이지 않지만) 
2. MainStatusView에서 현재 host 이름이 뜨는게 아니라, app storage 기본값 host가 뜬다

이 이슈와 연관지어서 fix하면 될까요?

**Comment by leewanjae** [comment]
맞아용~!! 늦게 답드려서 죄송합니당
