### ISSUE TITLE
[feat] share test

### ISSUE THREAD

**Issue by TopiaYu** [DeveloperAcademy-POSTECH/2024-MacC-A2-PohangEgrets#74]
## 🍏 About
* shareplay kit

## 🍀 Branch Name
feat/#74

## 🌱 To do
- [ shareplay kit 을 활용해서 한 번 테스트해볼게요 ]

**Comment by InKyungLee** [comment]
이거 이미 진행되었나요~? 제가 이 부분 구현하기로 했오요

**Comment by TopiaYu** [comment]
아니요 ~! 부탁드리겠습니다 선생님 ₩1
